2024-1008-01) 테이블생성
사용형식)
  CREATE TABLE 테이블명(
    컬럼명 데이터타입  [NOT NULL] [DEFAULT 값] [,]
    
    컬럼명 데이터타입  [NOT NULL] [DEFAULT 값] [,]
    
    [CONSTRAINT 제약이름 PRIMARY KEY(컴럼명[,...])][,]
    [CONSTRAINT 제약이름 FOREIGN KEY(컴럼명) REFERENCES 테이블명(컬럼명)][,]
    
    [CONSTRAINT 제약이름 FOREIGN KEY(컴럼명) REFERENCES 테이블명(컬럼명)][,];
    
사용예) 상품테이블 생성
  CREATE TABLE GOODS (
    GID CHAR(4), 
    G_NAME VARCHAR2(50),
    G_PRICE NUMBER(6),
    CONSTRAINT pk_goods PRIMARY KEY(GID));
    
  CREATE TABLE CUSTOMERS (
    CUST_ID NUMBER(4),
    CUST_NMAE VARCHAR2(30) NOT NULL,
    CUST_ADDR VARCHAR2(250),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY(CUST_ID));
    
  CREATE TABLE ORDERS(
    ORDER_NUM CHAR(12),
    CUST_ID  NUMBER(4),
    CONSTRAINT PK_ORDERS PRIMARY KEY(ORDER_NUM),
    CONSTRAINT FK_ORD_CUST FOREIGN KEY(CUST_ID)
      REFERENCES CUSTOMERS(CUST_ID));

DROP TABLE OERDER_GOODS;
  CREATE TABLE ORDER_GOODS(
    GID CHAR(4),
    ORDER_NUM  CHAR(12),
    ORDER_QTY NUMBER(3),
    CONSTRAINT PK_ORDS_GOODS PRIMARY KEY(GID, ORDER_NUM),
    CONSTRAINT FK_OR_GO FOREIGN KEY(GID)
      REFERENCES GOODS(GID),
    CONSTRAINT FK_ODGO_ORD FOREIGN KEY(ORDER_NUM)
      REFERENCES ORDERS(ORDER_NUM));
    
    