2024-1105-02)
1. 사원테이블에서 사원번호,사원명,부서코드,입사일,직무코드로 구성된 테이블 TBL_EMP를 생성하시오

  CREATE TABLE TBL_EMP AS
    SELECT EMPLOYEE_ID,EMP_NAME,DEPARTMENT_ID,HIRE_DATE,JOB_ID
      FROM EMPLOYEES;
      
2. 테이블 TBL_EMP와 같은 구조의 RETIRES 테이블을 생성하시오
  CREATE TABLE RETIRES AS
    SELECT *  FROM TBL_EMP;  
    
  DELETE FROM  RETIRES; 
  
  
사용예)TBL_EMP테이블에서 입사일이 2016년 이전사원들을 퇴직처리하시오
      퇴직처리는 퇴직자 정보를 RETIRES테이블에 저장하고 TBL_EMP테이블에서 삭제하는 작업 
  SELECT * FROM TBL_EMP
    WHERE HIRE_DATE<=TO_DATE('20160101');
    
  CREATE OR REPLACE TRIGGER tg_retire
    BEFORE  DELETE  ON  TBL_EMP
    FOR EACH ROW
  BEGIN
    INSERT INTO RETIRES(EMPLOYEE_ID, EMP_NAME, DEPARTMENT_ID, HIRE_DATE, JOB_ID)
      VALUES(:OLD.EMPLOYEE_ID, :OLD.EMP_NAME, :OLD.DEPARTMENT_ID, :OLD.HIRE_DATE, :OLD.JOB_ID);
  END;
  
    DELETE  FROM TBL_EMP
     WHERE HIRE_DATE<=TO_DATE('20160101');
