  CREATE TABLE DEPARTMENT(
  DEPT_ID  NUMBER(5),
  DEPT_NAME  VARCHAR2(30),
  DEPT_TEL  VARCHAR2(30),
  CONSTRAINT pk_DE_ID PRIMARY KEY(DEPT_ID));
  
  
  CREATE TABLE STUDENTS(
  STUD_ID  VARCHAR2(13),
  STUD_NAME  VARCHAR2(30),
  STUD_TEL  VARCHAR2(30),
  STUD_EMAIL VARCHAR2(50),
  STUD_ZIPCODE  VARCHAR2(10),
  STUD_ADD1 VARCHAR2(255),
  STUD_ADD2  VARCHAR2(100),
  DEPT_ID NUMBER(5)
  CONSTRAINT pk_ST_ID1 PRIMARY KEY(STUD_ID),
  CONSTRAINT FK_DE_ST1 FOREIGN KEY(DEPT_ID)
  REFERENCES DEPARTMENT(DEPT_ID));
  
  -------------------------------
  
   CREATE TABLE PROFESSOR(
  P_ID  NUMBER(3),
  P_NAME  VARCHAR2(30),
  P_MAJOR  VARCHAR2(50),
  P_TEL  VARCHAR2(30),
  DEPT_ID NUMBER(5),
  CONSTRAINT pk_PRO_ID2 PRIMARY KEY(P_ID),
  CONSTRAINTS fk_de_pro2 FOREIGN KEY(DEPT_ID)
   REFERENCES DEPARTMENT(DEPT_ID));
  
   CREATE TABLE LECTURE(
  LEC_ID  VARCHAR2(5),
  LEC_NAME  VARCHAR2(50),
  CREDIT  VARCHAR2(1),
  CONSTRAINT pk_LE_ID3 PRIMARY KEY(LEC_ID));
  
  
  
   CREATE TABLE OPEN_COURSE(
  OC_ID  VARCHAR2(5),
  OC_TOTAL_TIME  NUMBER(1),
  LEC_ID  VARCHAR2(5),
  P_ID  NUMBER(3),
  CONSTRAINT pk_OP_ID4 PRIMARY KEY(OC_ID),
  CONSTRAINT FK_LEC_op4 FOREIGN KEY(LEC_ID)
  REFERENCES LECTURE(LEC_ID),
  CONSTRAINT FK_PRO_OP4 FOREIGN KEY(P_ID)
  REFERENCES PROFESSOR(P_ID));
  
   CREATE TABLE OPEN_COURSE_INFO(
  OC_SEQ  NUMBER(1),
  OC_ID  VARCHAR2(5),
  OC_WEEK  VARCHAR2(10),
  OC_TIME  NUMBER(1),
  OC_ROOM  VARCHAR2(5),
  OC_PERIOD  VARCHAR2(2),
  CONSTRAINT pk_OPEN5 PRIMARY KEY(OC_SEQ),
  CONSTRAINT FK_OP_INFO5 FOREIGN KEY(OC_ID)
  REFERENCES OPEN_COURSE(OC_ID));
  
  
  
  CREATE TABLE ENROLLMENT(
  OC_ID  VARCHAR2(5),
  STUD_ID  VARCHAR2(13),
  FINAL_SCORE  NUMBER(3),
  CONSTRAINT pk_ENRO6 PRIMARY KEY(OC_ID, STUD_ID),
  CONSTRAINT FK_ENRO_OP6 FOREIGN KEY(OC_ID)
  REFERENCES OPEN_COURSE(OC_ID),
  CONSTRAINT FK_ENRO_ST6 FOREIGN KEY(STUD_ID)
  REFERENCES STUDENTS(STUD_ID));
  
  
      CREATE TABLE TEST_TYPE(
  T_TYPE  NUMBER(2),
  TYPE_NAME  VARCHAR2(30),
  CONSTRAINT pk_TEST7 PRIMARY KEY(T_TYPE));


  
  
  CREATE TABLE EVALUATION2(
  OC_ID  VARCHAR2(5),
  STUD_ID  VARCHAR2(13),
  T_TYPE  NUMBER(2),
  E_SCORE NUMBER(3),
  CONSTRAINT pk_EVAL123 PRIMARY KEY(OC_ID, STUD_ID, T_TYPE),
  CONSTRAINT FK_EVAL_OC8 FOREIGN KEY(OC_ID)
  REFERENCES OPEN_COURSE(OC_ID),
  CONSTRAINT FK_ENRO_ST8 FOREIGN KEY(STUD_ID)
  REFERENCES STUDENTS(STUD_ID),
    CONSTRAINT FK_ENRO_TY8 FOREIGN KEY(T_TYPE)
  REFERENCES TEST_TYPE(T_TYPE));
  
  